[package]
name = "gof-conformance"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
gof-compiler = { path = "../../compiler/gof-compiler" }

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
roxmltree.workspace = true
serde_json.workspace = true
tempfile.workspace = true

